"""add projects and tickets tables

Revision ID: 014dd7db10b8
Revises: 243540ac6fd8
Create Date: 2025-11-19 04:20:54.178183

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "014dd7db10b8"
down_revision: Union[str, Sequence[str], None] = "243540ac6fd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column("ai_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_index(
        op.f("ix_projects_organization_id"),
        "projects",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("assigned_to", sa.Uuid(), nullable=True),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column(
            "priority", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tickets_assigned_to"), "tickets", ["assigned_to"], unique=False
    )
    op.create_index(
        op.f("ix_tickets_created_by"), "tickets", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_tickets_id"), "tickets", ["id"], unique=False)
    op.create_index(
        op.f("ix_tickets_organization_id"), "tickets", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_tickets_priority"), "tickets", ["priority"], unique=False)
    op.create_index(
        op.f("ix_tickets_project_id"), "tickets", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_tickets_status"), "tickets", ["status"], unique=False)
    op.create_index(op.f("ix_tickets_title"), "tickets", ["title"], unique=False)
    op.add_column(
        "organizations",
        sa.Column(
            "industry", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
    )
    op.alter_column(
        "organizations",
        "settings",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "organizations",
        "billing_info",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.add_column("roles", sa.Column("organization_id", sa.Uuid(), nullable=False))
    op.alter_column(
        "roles",
        "permissions",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=False)
    op.create_index(
        op.f("ix_roles_organization_id"), "roles", ["organization_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_org_role_name", "roles", ["organization_id", "name"]
    )
    op.create_foreign_key(None, "roles", "organizations", ["organization_id"], ["id"])
    op.add_column(
        "users",
        sa.Column(
            "auth_provider", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "auth_provider")
    op.drop_constraint(None, "roles", type_="foreignkey")
    op.drop_constraint("uq_org_role_name", "roles", type_="unique")
    op.drop_index(op.f("ix_roles_organization_id"), table_name="roles")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.alter_column(
        "roles",
        "permissions",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_column("roles", "organization_id")
    op.alter_column(
        "organizations",
        "billing_info",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "organizations",
        "settings",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_column("organizations", "industry")
    op.drop_index(op.f("ix_tickets_title"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_status"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_project_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_priority"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_organization_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_created_by"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_assigned_to"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_index(op.f("ix_projects_organization_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
