"""Add ticket collaboration models

Revision ID: 06e603623325
Revises: bf283f4bc632
Create Date: 2025-12-04 22:28:22.078421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06e603623325'
down_revision: Union[str, Sequence[str], None] = 'bf283f4bc632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create guests table
    op.create_table('guests',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('invited_by_user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guests_email'), 'guests', ['email'], unique=False)
    op.create_index(op.f('ix_guests_id'), 'guests', ['id'], unique=False)
    op.create_index(op.f('ix_guests_invited_by_user_id'), 'guests', ['invited_by_user_id'], unique=False)
    
    # Create enums first
    op.execute("CREATE TYPE participanttype AS ENUM ('USER', 'GUEST')")
    op.execute("CREATE TYPE accesslevel AS ENUM ('VIEWER', 'COMMENTER', 'EDITOR')")
    
    # Create ticket_participants table
    op.create_table('ticket_participants',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('ticket_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('participant_type', sa.Enum('USER', 'GUEST', name='participanttype'), nullable=False),
        sa.Column('participant_user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('participant_guest_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('access_level', sa.Enum('VIEWER', 'COMMENTER', 'EDITOR', name='accesslevel'), nullable=False),
        sa.Column('invited_by_user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_assigned_responder', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['participant_guest_id'], ['guests.id'], ),
        sa.ForeignKeyConstraint(['participant_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_participants_id'), 'ticket_participants', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_participants_participant_guest_id'), 'ticket_participants', ['participant_guest_id'], unique=False)
    op.create_index(op.f('ix_ticket_participants_participant_user_id'), 'ticket_participants', ['participant_user_id'], unique=False)
    op.create_index(op.f('ix_ticket_participants_ticket_id'), 'ticket_participants', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_participants_invited_by_user_id'), 'ticket_participants', ['invited_by_user_id'], unique=False)
    
    # Create magic_links table
    op.create_table('magic_links',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('token', sa.String(length=255), nullable=False),
        sa.Column('guest_email', sa.String(length=255), nullable=False),
        sa.Column('ticket_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_by_user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('max_uses', sa.Integer(), nullable=False),
        sa.Column('use_count', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_magic_links_created_by_user_id'), 'magic_links', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_magic_links_guest_email'), 'magic_links', ['guest_email'], unique=False)
    op.create_index(op.f('ix_magic_links_id'), 'magic_links', ['id'], unique=False)
    op.create_index(op.f('ix_magic_links_ticket_id'), 'magic_links', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_magic_links_token'), 'magic_links', ['token'], unique=True)
    
    # Create ticket_comments table
    op.create_table('ticket_comments',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('ticket_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('author_type', sa.String(), nullable=False),
        sa.Column('author_user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('author_guest_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('author_name', sa.String(length=255), nullable=False),
        sa.Column('author_email', sa.String(length=255), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('is_internal', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['author_guest_id'], ['guests.id'], ),
        sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_comments_author_guest_id'), 'ticket_comments', ['author_guest_id'], unique=False)
    op.create_index(op.f('ix_ticket_comments_author_user_id'), 'ticket_comments', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_ticket_comments_id'), 'ticket_comments', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_comments_ticket_id'), 'ticket_comments', ['ticket_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_comments_ticket_id'), table_name='ticket_comments')
    op.drop_index(op.f('ix_ticket_comments_id'), table_name='ticket_comments')
    op.drop_index(op.f('ix_ticket_comments_author_user_id'), table_name='ticket_comments')
    op.drop_index(op.f('ix_ticket_comments_author_guest_id'), table_name='ticket_comments')
    op.drop_table('ticket_comments')
    
    op.drop_index(op.f('ix_magic_links_token'), table_name='magic_links')
    op.drop_index(op.f('ix_magic_links_ticket_id'), table_name='magic_links')
    op.drop_index(op.f('ix_magic_links_id'), table_name='magic_links')
    op.drop_index(op.f('ix_magic_links_guest_email'), table_name='magic_links')
    op.drop_index(op.f('ix_magic_links_created_by_user_id'), table_name='magic_links')
    op.drop_table('magic_links')
    
    op.drop_index(op.f('ix_ticket_participants_invited_by_user_id'), table_name='ticket_participants')
    op.drop_index(op.f('ix_ticket_participants_ticket_id'), table_name='ticket_participants')
    op.drop_index(op.f('ix_ticket_participants_participant_user_id'), table_name='ticket_participants')
    op.drop_index(op.f('ix_ticket_participants_participant_guest_id'), table_name='ticket_participants')
    op.drop_index(op.f('ix_ticket_participants_id'), table_name='ticket_participants')
    op.drop_table('ticket_participants')
    
    # Drop the enums
    op.execute('DROP TYPE IF EXISTS accesslevel')
    op.execute('DROP TYPE IF EXISTS participanttype')
    
    op.drop_index(op.f('ix_guests_invited_by_user_id'), table_name='guests')
    op.drop_index(op.f('ix_guests_id'), table_name='guests')
    op.drop_index(op.f('ix_guests_email'), table_name='guests')
    op.drop_table('guests')
    # ### end Alembic commands ###