"""add_ticket_invitations_table

Revision ID: 0df8e9784964
Revises: 014dd7db10b8
Create Date: 2025-11-19 05:14:43.763660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0df8e9784964'
down_revision: Union[str, Sequence[str], None] = '014dd7db10b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('invitee_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.Uuid(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_invitations_id'), 'ticket_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_invitations_invited_by'), 'ticket_invitations', ['invited_by'], unique=False)
    op.create_index(op.f('ix_ticket_invitations_invitee_email'), 'ticket_invitations', ['invitee_email'], unique=False)
    op.create_index(op.f('ix_ticket_invitations_revoked_by'), 'ticket_invitations', ['revoked_by'], unique=False)
    op.create_index(op.f('ix_ticket_invitations_ticket_id'), 'ticket_invitations', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_invitations_token'), 'ticket_invitations', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_invitations_token'), table_name='ticket_invitations')
    op.drop_index(op.f('ix_ticket_invitations_ticket_id'), table_name='ticket_invitations')
    op.drop_index(op.f('ix_ticket_invitations_revoked_by'), table_name='ticket_invitations')
    op.drop_index(op.f('ix_ticket_invitations_invitee_email'), table_name='ticket_invitations')
    op.drop_index(op.f('ix_ticket_invitations_invited_by'), table_name='ticket_invitations')
    op.drop_index(op.f('ix_ticket_invitations_id'), table_name='ticket_invitations')
    op.drop_table('ticket_invitations')
    # ### end Alembic commands ###
