"""Create data_revision and change_diff tables

Revision ID: 1209760cdb27
Revises: dd94c68c2ed7
Create Date: 2025-11-21 07:55:24.794030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1209760cdb27'
down_revision: Union[str, Sequence[str], None] = 'dd94c68c2ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_diff',
    sa.Column('diff_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('new_revision_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_revision_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('diff_patch', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('diff_id')
    )
    op.create_table('data_revision',
    sa.Column('revision_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('was_change_detected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('revision_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_revision')
    op.drop_table('change_diff')
    # ### end Alembic commands ###
