"""add scrape_job_id and  revision_id optional

Revision ID: 2600fdafcd64
Revises: a249039be841
Create Date: 2025-12-05 18:11:18.375017

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2600fdafcd64'
down_revision: Union[str, Sequence[str], None] = 'a249039be841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_code'), 'otps', ['code'], unique=False)
    op.create_index(op.f('ix_otps_id'), 'otps', ['id'], unique=False)
    op.create_index(op.f('ix_otps_user_id'), 'otps', ['user_id'], unique=False)
    op.create_table('revision_notifications',
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('revision_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('scrape_job_id', sa.Uuid(), nullable=True),
    sa.Column('notification_type', sa.Enum('MENTION', 'CHANGE_DETECTED', 'SCRAPE_FAILED', name='notificationtype'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('jurisdiction_id', sa.Uuid(), nullable=True),
    sa.Column('change_diff_id', sa.Uuid(), nullable=True),
    sa.Column('action_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['change_diff_id'], ['change_diff.diff_id'], ),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['data_revisions.id'], ),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index('ix_notifications_scrape_job', 'revision_notifications', ['scrape_job_id'], unique=False, postgresql_where=sa.text('scrape_job_id IS NOT NULL'))
    op.create_index('ix_notifications_type_created', 'revision_notifications', ['notification_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_notifications_unread', 'revision_notifications', ['user_id'], unique=False, postgresql_where=sa.text('read_at IS NULL'))
    op.create_index('ix_notifications_user_created', 'revision_notifications', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_notifications_user_status', 'revision_notifications', ['user_id', 'status'], unique=False, postgresql_where=sa.text('read_at IS NULL'))
    op.create_index(op.f('ix_revision_notifications_change_diff_id'), 'revision_notifications', ['change_diff_id'], unique=False)
    op.create_index(op.f('ix_revision_notifications_jurisdiction_id'), 'revision_notifications', ['jurisdiction_id'], unique=False)
    op.create_index(op.f('ix_revision_notifications_organization_id'), 'revision_notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_revision_notifications_revision_id'), 'revision_notifications', ['revision_id'], unique=False)
    op.create_index(op.f('ix_revision_notifications_scrape_job_id'), 'revision_notifications', ['scrape_job_id'], unique=False)
    op.create_index(op.f('ix_revision_notifications_source_id'), 'revision_notifications', ['source_id'], unique=False)
    op.create_index(op.f('ix_revision_notifications_status'), 'revision_notifications', ['status'], unique=False)
    op.add_column('roles', sa.Column('hierarchy_level', sa.Integer(), nullable=False))
    op.add_column('roles', sa.Column('template_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.alter_column('roles', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_column('roles', 'template_name')
    op.drop_column('roles', 'hierarchy_level')
    op.drop_index(op.f('ix_revision_notifications_status'), table_name='revision_notifications')
    op.drop_index(op.f('ix_revision_notifications_source_id'), table_name='revision_notifications')
    op.drop_index(op.f('ix_revision_notifications_scrape_job_id'), table_name='revision_notifications')
    op.drop_index(op.f('ix_revision_notifications_revision_id'), table_name='revision_notifications')
    op.drop_index(op.f('ix_revision_notifications_organization_id'), table_name='revision_notifications')
    op.drop_index(op.f('ix_revision_notifications_jurisdiction_id'), table_name='revision_notifications')
    op.drop_index(op.f('ix_revision_notifications_change_diff_id'), table_name='revision_notifications')
    op.drop_index('ix_notifications_user_status', table_name='revision_notifications', postgresql_where=sa.text('read_at IS NULL'))
    op.drop_index('ix_notifications_user_created', table_name='revision_notifications')
    op.drop_index('ix_notifications_unread', table_name='revision_notifications', postgresql_where=sa.text('read_at IS NULL'))
    op.drop_index('ix_notifications_type_created', table_name='revision_notifications')
    op.drop_index('ix_notifications_scrape_job', table_name='revision_notifications', postgresql_where=sa.text('scrape_job_id IS NOT NULL'))
    op.drop_table('revision_notifications')
    op.drop_index(op.f('ix_otps_user_id'), table_name='otps')
    op.drop_index(op.f('ix_otps_id'), table_name='otps')
    op.drop_index(op.f('ix_otps_code'), table_name='otps')
    op.drop_table('otps')
    # ### end Alembic commands ###
