"""Initial migrations

Revision ID: 3de8acaaa3e8
Revises: d6fbd06a73d2
Create Date: 2025-11-18 10:43:27.302174

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3de8acaaa3e8"
down_revision: Union[str, Sequence[str], None] = "d6fbd06a73d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onboarding",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "signup_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "organization_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["organization_email"],
            ["waitlist.organization_email"],
        ),
        sa.PrimaryKeyConstraint("email"),
    )
    op.create_index(op.f("ix_onboarding_email"), "onboarding", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_onboarding_email"), table_name="onboarding")
    op.drop_table("onboarding")
    # ### end Alembic commands ###
