"""add project regulatory source model

Revision ID: 447e8baa6eee
Revises: dd94c68c2ed7
Create Date: 2025-11-21 00:03:59.241367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '447e8baa6eee'
down_revision: Union[str, Sequence[str], None] = 'dd94c68c2ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_regulatory_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_regulatory_sources_id'), 'project_regulatory_sources', ['id'], unique=False)
    op.create_index(op.f('ix_project_regulatory_sources_project_id'), 'project_regulatory_sources', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_regulatory_sources_project_id'), table_name='project_regulatory_sources')
    op.drop_index(op.f('ix_project_regulatory_sources_id'), table_name='project_regulatory_sources')
    op.drop_table('project_regulatory_sources')
    # ### end Alembic commands ###
