"""Add last_scraped_at to Source model

Revision ID: 595ffa06efd5
Revises: 639ff4afb64a
Create Date: 2025-11-27 12:03:23.180903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '595ffa06efd5'
down_revision: Union[str, Sequence[str], None] = '639ff4afb64a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sources', sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'last_error')
    op.drop_column('sources', 'last_scraped_at')
    # ### end Alembic commands ###
