"""create jurisdictions table

Revision ID: 5c95b9654b9b
Revises: 642bebb50756
Create Date: 2025-12-04 13:37:22.278676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '5c95b9654b9b'
down_revision: Union[str, Sequence[str], None] = '642bebb50756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_audit_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('jurisdiction_id', sa.Uuid(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action', postgresql.ENUM('PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_DELETED', 'JURISDICTION_CREATED', 'JURISDICTION_UPDATED', 'JURISDICTION_DELETED', 'JURISDICTION_PARENT_CHANGED', 'MASTER_PROMPT_UPDATED', 'OVERRIDE_PROMPT_UPDATED', 'SOURCE_ASSIGNED', 'SOURCE_UNASSIGNED', 'SOURCE_UPDATED', name='auditaction'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_project_audit_log_action'), 'project_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_project_audit_log_jurisdiction_id'), 'project_audit_log', ['jurisdiction_id'], unique=False)
    op.create_index(op.f('ix_project_audit_log_org_id'), 'project_audit_log', ['org_id'], unique=False)
    op.create_index(op.f('ix_project_audit_log_project_id'), 'project_audit_log', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_audit_log_source_id'), 'project_audit_log', ['source_id'], unique=False)
    op.create_index(op.f('ix_project_audit_log_user_id'), 'project_audit_log', ['user_id'], unique=False)
    op.add_column('jurisdictions', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('jurisdictions', sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('jurisdictions', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('jurisdictions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_jurisdictions_name'), 'jurisdictions', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jurisdictions_name'), table_name='jurisdictions')
    op.drop_column('jurisdictions', 'is_active')
    op.drop_column('jurisdictions', 'city')
    op.drop_column('jurisdictions', 'state')
    op.drop_column('jurisdictions', 'country')
    op.drop_index(op.f('ix_project_audit_log_user_id'), table_name='project_audit_log')
    op.drop_index(op.f('ix_project_audit_log_source_id'), table_name='project_audit_log')
    op.drop_index(op.f('ix_project_audit_log_project_id'), table_name='project_audit_log')
    op.drop_index(op.f('ix_project_audit_log_org_id'), table_name='project_audit_log')
    op.drop_index(op.f('ix_project_audit_log_jurisdiction_id'), table_name='project_audit_log')
    op.drop_index(op.f('ix_project_audit_log_action'), table_name='project_audit_log')
    op.drop_table('project_audit_log')
    # ### end Alembic commands ###
