"""add columns to revision notification table

Revision ID: 6a218a6d6a3e
Revises: 642bebb50756
Create Date: 2025-12-04 19:32:55.429831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a218a6d6a3e'
down_revision: Union[str, Sequence[str], None] = '642bebb50756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revision_notifications', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('revision_notifications', sa.Column('source_id', sa.Uuid(), nullable=True))
    op.add_column('revision_notifications', sa.Column('notification_type', sa.Enum('MENTION', 'CHANGE_DETECTED', 'SCRAPE_FAILED', name='notificationtype'), nullable=False))
    op.add_column('revision_notifications', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.add_column('revision_notifications', sa.Column('change_diff_id', sa.Uuid(), nullable=True))
    op.add_column('revision_notifications', sa.Column('action_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.add_column('revision_notifications', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('revision_notifications', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SENT', 'FAILED', name='notificationstatus'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('revision_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('revision_notifications', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index('ix_notifications_type_created', 'revision_notifications', ['notification_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_notifications_unread', 'revision_notifications', ['user_id'], unique=False, postgresql_where=sa.text('read_at IS NULL'))
    op.create_index('ix_notifications_user_created', 'revision_notifications', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_notifications_user_status', 'revision_notifications', ['user_id', 'status'], unique=False, postgresql_where=sa.text('read_at IS NULL'))
    op.create_index(op.f('ix_revision_notifications_change_diff_id'), 'revision_notifications', ['change_diff_id'], unique=False)
    op.create_index(op.f('ix_revision_notifications_organization_id'), 'revision_notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_revision_notifications_revision_id'), 'revision_notifications', ['revision_id'], unique=False)
    op.create_index(op.f('ix_revision_notifications_source_id'), 'revision_notifications', ['source_id'], unique=False)
    op.create_index(op.f('ix_revision_notifications_status'), 'revision_notifications', ['status'], unique=False)
    op.create_foreign_key(None, 'revision_notifications', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'revision_notifications', 'sources', ['source_id'], ['id'])
    op.create_foreign_key(None, 'revision_notifications', 'change_diff', ['change_diff_id'], ['diff_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'revision_notifications', type_='foreignkey')
    op.drop_constraint(None, 'revision_notifications', type_='foreignkey')
    op.drop_constraint(None, 'revision_notifications', type_='foreignkey')
    op.drop_index(op.f('ix_revision_notifications_status'), table_name='revision_notifications')
    op.drop_index(op.f('ix_revision_notifications_source_id'), table_name='revision_notifications')
    op.drop_index(op.f('ix_revision_notifications_revision_id'), table_name='revision_notifications')
    op.drop_index(op.f('ix_revision_notifications_organization_id'), table_name='revision_notifications')
    op.drop_index(op.f('ix_revision_notifications_change_diff_id'), table_name='revision_notifications')
    op.drop_index('ix_notifications_user_status', table_name='revision_notifications', postgresql_where=sa.text('read_at IS NULL'))
    op.drop_index('ix_notifications_user_created', table_name='revision_notifications')
    op.drop_index('ix_notifications_unread', table_name='revision_notifications', postgresql_where=sa.text('read_at IS NULL'))
    op.drop_index('ix_notifications_type_created', table_name='revision_notifications')
    op.alter_column('revision_notifications', 'sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('revision_notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('revision_notifications', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PENDING', 'SENT', 'FAILED', name='notificationstatus'),
               existing_nullable=False)
    op.drop_column('revision_notifications', 'read_at')
    op.drop_column('revision_notifications', 'action_url')
    op.drop_column('revision_notifications', 'change_diff_id')
    op.drop_column('revision_notifications', 'organization_id')
    op.drop_column('revision_notifications', 'notification_type')
    op.drop_column('revision_notifications', 'source_id')
    op.drop_column('revision_notifications', 'title')
    # ### end Alembic commands ###
