"""Add scrape_job_id to revision_notifications

Revision ID: 6d3c7b3a39ee
Revises: d227f5996841
Create Date: 2025-12-05 04:58:37.255181

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d3c7b3a39ee'
down_revision: Union[str, Sequence[str], None] = 'd227f5996841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    notification_type_enum = postgresql.ENUM(
        'MENTION', 'CHANGE_DETECTED', 'SCRAPE_FAILED', name='notificationtype'
    )
    notification_type_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_code'), 'otps', ['code'], unique=False)
    op.create_index(op.f('ix_otps_id'), 'otps', ['id'], unique=False)
    op.create_index(op.f('ix_otps_user_id'), 'otps', ['user_id'], unique=False)
    op.create_table('scrape_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='scrapejobstatus'), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_revision_id', sa.Uuid(), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['data_revision_id'], ['data_revisions.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_jobs_data_revision_id'), 'scrape_jobs', ['data_revision_id'], unique=False)
    op.create_index(op.f('ix_scrape_jobs_id'), 'scrape_jobs', ['id'], unique=False)
    op.create_index('ix_scrape_jobs_source_active', 'scrape_jobs', ['source_id'], unique=True, postgresql_where="status IN ('PENDING', 'IN_PROGRESS')")
    op.create_index(op.f('ix_scrape_jobs_source_id'), 'scrape_jobs', ['source_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority'), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('data_revision_id', sa.Uuid(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['data_revision_id'], ['data_revisions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_assigned_by_user_id'), 'tickets', ['assigned_by_user_id'], unique=False)
    op.create_index(op.f('ix_tickets_assigned_to_user_id'), 'tickets', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_tickets_created_by_user_id'), 'tickets', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_tickets_data_revision_id'), 'tickets', ['data_revision_id'], unique=False)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_organization_id'), 'tickets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_project_id'), 'tickets', ['project_id'], unique=False)
    op.create_index(op.f('ix_tickets_source_id'), 'tickets', ['source_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_title'), 'tickets', ['title'], unique=False)
    op.create_table('ticket_invited_users',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'user_id')
    )
    op.create_index(op.f('ix_ticket_invited_users_ticket_id'), 'ticket_invited_users', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_invited_users_user_id'), 'ticket_invited_users', ['user_id'], unique=False)
    op.drop_table('testuser')
    op.add_column('data_revisions', sa.Column('is_baseline', sa.Boolean(), nullable=False))
    op.create_index('ix_org_active_not_deleted', 'organizations', ['is_active'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.add_column('revision_notifications', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('revision_notifications', sa.Column('source_id', sa.Uuid(), nullable=True))
    op.add_column('revision_notifications', sa.Column('scrape_job_id', sa.Uuid(), nullable=True))
    op.add_column('revision_notifications', sa.Column('notification_type', sa.Enum('MENTION', 'CHANGE_DETECTED', 'SCRAPE_FAILED', name='notificationtype'), nullable=False))
    op.add_column('revision_notifications', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.add_column('revision_notifications', sa.Column('jurisdiction_id', sa.Uuid(), nullable=True))
    op.add_column('revision_notifications', sa.Column('change_diff_id', sa.Uuid(), nullable=True))
    op.add_column('revision_notifications', sa.Column('action_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.add_column('revision_notifications', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('revision_notifications', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SENT', 'FAILED', name='notificationstatus'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('revision_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('revision_notifications', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index('ix_notifications_scrape_job', 'revision_notifications', ['scrape_job_id'], unique=False, postgresql_where=sa.text('scrape_job_id IS NOT NULL'))
    op.create_index('ix_notifications_type_created', 'revision_notifications', ['notification_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_notifications_unread', 'revision_notifications', ['user_id'], unique=False, postgresql_where=sa.text('read_at IS NULL'))
    op.create_index('ix_notifications_user_created', 'revision_notifications', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_notifications_user_status', 'revision_notifications', ['user_id', 'status'], unique=False, postgresql_where=sa.text('read_at IS NULL'))
    op.create_index(op.f('ix_revision_notifications_change_diff_id'), 'revision_notifications', ['change_diff_id'], unique=False)
    op.create_index(op.f('ix_revision_notifications_jurisdiction_id'), 'revision_notifications', ['jurisdiction_id'], unique=False)
    op.create_index(op.f('ix_revision_notifications_organization_id'), 'revision_notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_revision_notifications_revision_id'), 'revision_notifications', ['revision_id'], unique=False)
    op.create_index(op.f('ix_revision_notifications_scrape_job_id'), 'revision_notifications', ['scrape_job_id'], unique=False)
    op.create_index(op.f('ix_revision_notifications_source_id'), 'revision_notifications', ['source_id'], unique=False)
    op.create_index(op.f('ix_revision_notifications_status'), 'revision_notifications', ['status'], unique=False)
    op.create_foreign_key(None, 'revision_notifications', 'sources', ['source_id'], ['id'])
    op.create_foreign_key(None, 'revision_notifications', 'scrape_jobs', ['scrape_job_id'], ['id'])
    op.create_foreign_key(None, 'revision_notifications', 'change_diff', ['change_diff_id'], ['diff_id'])
    op.create_foreign_key(None, 'revision_notifications', 'jurisdictions', ['jurisdiction_id'], ['id'])
    op.create_foreign_key(None, 'revision_notifications', 'organizations', ['organization_id'], ['id'])
    op.create_index('ix_user_org_active_memberships', 'user_organizations', ['user_id', 'is_active'], unique=False, postgresql_where=sa.text('is_deleted IS false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_org_active_memberships', table_name='user_organizations', postgresql_where=sa.text('is_deleted IS false'))
    op.drop_constraint(None, 'revision_notifications', type_='foreignkey')
    op.drop_constraint(None, 'revision_notifications', type_='foreignkey')
    op.drop_constraint(None, 'revision_notifications', type_='foreignkey')
    op.drop_constraint(None, 'revision_notifications', type_='foreignkey')
    op.drop_constraint(None, 'revision_notifications', type_='foreignkey')
    op.drop_index(op.f('ix_revision_notifications_status'), table_name='revision_notifications')
    op.drop_index(op.f('ix_revision_notifications_source_id'), table_name='revision_notifications')
    op.drop_index(op.f('ix_revision_notifications_scrape_job_id'), table_name='revision_notifications')
    op.drop_index(op.f('ix_revision_notifications_revision_id'), table_name='revision_notifications')
    op.drop_index(op.f('ix_revision_notifications_organization_id'), table_name='revision_notifications')
    op.drop_index(op.f('ix_revision_notifications_jurisdiction_id'), table_name='revision_notifications')
    op.drop_index(op.f('ix_revision_notifications_change_diff_id'), table_name='revision_notifications')
    op.drop_index('ix_notifications_user_status', table_name='revision_notifications', postgresql_where=sa.text('read_at IS NULL'))
    op.drop_index('ix_notifications_user_created', table_name='revision_notifications')
    op.drop_index('ix_notifications_unread', table_name='revision_notifications', postgresql_where=sa.text('read_at IS NULL'))
    op.drop_index('ix_notifications_type_created', table_name='revision_notifications')
    op.drop_index('ix_notifications_scrape_job', table_name='revision_notifications', postgresql_where=sa.text('scrape_job_id IS NOT NULL'))
    op.alter_column('revision_notifications', 'sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('revision_notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('revision_notifications', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PENDING', 'SENT', 'FAILED', name='notificationstatus'),
               existing_nullable=False)
    op.drop_column('revision_notifications', 'read_at')
    op.drop_column('revision_notifications', 'action_url')
    op.drop_column('revision_notifications', 'change_diff_id')
    op.drop_column('revision_notifications', 'jurisdiction_id')
    op.drop_column('revision_notifications', 'organization_id')
    op.drop_column('revision_notifications', 'notification_type')
    op.drop_column('revision_notifications', 'scrape_job_id')
    op.drop_column('revision_notifications', 'source_id')
    op.drop_column('revision_notifications', 'title')
    op.drop_index('ix_org_active_not_deleted', table_name='organizations', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_column('data_revisions', 'is_baseline')
    op.create_table('testuser',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('testuser_pkey'))
    )
    op.drop_index(op.f('ix_ticket_invited_users_user_id'), table_name='ticket_invited_users')
    op.drop_index(op.f('ix_ticket_invited_users_ticket_id'), table_name='ticket_invited_users')
    op.drop_table('ticket_invited_users')
    op.drop_index(op.f('ix_tickets_title'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_source_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_project_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_organization_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_data_revision_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_created_by_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_to_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_by_user_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_scrape_jobs_source_id'), table_name='scrape_jobs')
    op.drop_index('ix_scrape_jobs_source_active', table_name='scrape_jobs', postgresql_where="status IN ('PENDING', 'IN_PROGRESS')")
    op.drop_index(op.f('ix_scrape_jobs_id'), table_name='scrape_jobs')
    op.drop_index(op.f('ix_scrape_jobs_data_revision_id'), table_name='scrape_jobs')
    op.drop_table('scrape_jobs')
    op.drop_index(op.f('ix_otps_user_id'), table_name='otps')
    op.drop_index(op.f('ix_otps_id'), table_name='otps')
    op.drop_index(op.f('ix_otps_code'), table_name='otps')
    op.drop_table('otps')
    # ### end Alembic commands ###
