"""Create diff table

Revision ID: 7d1fb4b20e75
Revises: 1ab5a062c90b
Create Date: 2025-11-24 13:28:39.327489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d1fb4b20e75'
down_revision: Union[str, Sequence[str], None] = '1ab5a062c90b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_diff',
    sa.Column('diff_id', sa.Uuid(), nullable=False),
    sa.Column('new_revision_id', sa.Uuid(), nullable=False),
    sa.Column('old_revision_id', sa.Uuid(), nullable=False),
    sa.Column('diff_patch', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['new_revision_id'], ['data_revisions.id'], ),
    sa.ForeignKeyConstraint(['old_revision_id'], ['data_revisions.id'], ),
    sa.PrimaryKeyConstraint('diff_id')
    )
    op.create_index(op.f('ix_change_diff_diff_id'), 'change_diff', ['diff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_diff_diff_id'), table_name='change_diff')
    op.drop_table('change_diff')
    # ### end Alembic commands ###
