"""create specialist_hires table

Revision ID: 924acaf3d7b8
Revises: fa7a4d7cccac
Create Date: 2025-11-28 16:50:57.891869

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924acaf3d7b8'
down_revision: Union[str, Sequence[str], None] = 'fa7a4d7cccac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialist_hires',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('company_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('brief_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialist_hires')
    # ### end Alembic commands ###
