"""create specialist_hires table

Revision ID: 924acaf3d7b8
Revises: fa7a4d7cccac
Create Date: 2025-11-28 16:50:57.891869

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '924acaf3d7b8'
down_revision: Union[str, Sequence[str], None] = 'fa7a4d7cccac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TABLE IF NOT EXISTS specialist_hires (
            id UUID NOT NULL,
            company_name VARCHAR(255) NOT NULL,
            company_email VARCHAR(255) NOT NULL,
            industry VARCHAR(255) NOT NULL,
            brief_description TEXT NOT NULL,
            created_at TIMESTAMP NOT NULL,
            PRIMARY KEY (id)
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialist_hires')
    # ### end Alembic commands ###
