"""APIKey and APIKeyToken Models

Revision ID: a2db59835404
Revises: d227f5996841
Create Date: 2025-12-05 12:25:06.275885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a2db59835404'
down_revision: Union[str, Sequence[str], None] = 'd227f5996841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('receiver_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('rotation_enabled', sa.Boolean(), nullable=False),
    sa.Column('rotation_interval_days', sa.Integer(), nullable=True),
    sa.Column('last_rotated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_key'),
    sa.UniqueConstraint('organization_id', 'key_name', name='uq_org_keyname')
    )
    op.create_index(op.f('ix_api_keys_generated_by'), 'api_keys', ['generated_by'], unique=False)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_organization_id'), 'api_keys', ['organization_id'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('api_key_onboarding_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('api_key_id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_api_key_onboarding_tokens_api_key_id'), 'api_key_onboarding_tokens', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_ticket_invited_users_ticket_id'), 'ticket_invited_users', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_invited_users_user_id'), 'ticket_invited_users', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_ticket_invited_users_ticket_id'), 'ticket_invited_users', type_='foreignkey')
    op.drop_constraint(op.f('fk_ticket_invited_users_user_id'), 'ticket_invited_users', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_invited_users', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'ticket_invited_users', 'tickets', ['ticket_id'], ['id'])
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_tickets_assigned_by_user_id'), 'tickets', ['assigned_by_user_id'], unique=False)
    op.create_index(op.f('ix_tickets_data_revision_id'), 'tickets', ['data_revision_id'], unique=False)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_source_id'), 'tickets', ['source_id'], unique=False)
    op.create_index(op.f('ix_tickets_title'), 'tickets', ['title'], unique=False)
    op.drop_constraint(op.f('fk_tickets_data_revision_id'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_organization_id'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_project_id'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_assigned_to_user_id'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_source_id'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_created_by_user_id'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_assigned_by_user_id'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'users', ['assigned_to_user_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'sources', ['source_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'users', ['assigned_by_user_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'data_revisions', ['data_revision_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tickets_assigned_by_user_id'), 'tickets', 'users', ['assigned_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_tickets_created_by_user_id'), 'tickets', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_tickets_source_id'), 'tickets', 'sources', ['source_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_tickets_assigned_to_user_id'), 'tickets', 'users', ['assigned_to_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_tickets_project_id'), 'tickets', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_tickets_organization_id'), 'tickets', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_tickets_data_revision_id'), 'tickets', 'data_revisions', ['data_revision_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_tickets_title'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_source_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_data_revision_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_by_user_id'), table_name='tickets')
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(None, 'ticket_invited_users', type_='foreignkey')
    op.drop_constraint(None, 'ticket_invited_users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ticket_invited_users_user_id'), 'ticket_invited_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_ticket_invited_users_ticket_id'), 'ticket_invited_users', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ticket_invited_users_user_id'), table_name='ticket_invited_users')
    op.drop_index(op.f('ix_ticket_invited_users_ticket_id'), table_name='ticket_invited_users')
    op.drop_index(op.f('ix_api_key_onboarding_tokens_api_key_id'), table_name='api_key_onboarding_tokens')
    op.drop_table('api_key_onboarding_tokens')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_organization_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_generated_by'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
