"""add delete relationships for project project users and jurisdiction

Revision ID: a3024baf3730
Revises: c1bc173efb4e
Create Date: 2025-11-21 17:21:14.485333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3024baf3730'
down_revision: Union[str, Sequence[str], None] = 'c1bc173efb4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('jurisdictions_project_id_fkey'), 'jurisdictions', type_='foreignkey')
    op.drop_constraint(op.f('jurisdictions_parent_id_fkey'), 'jurisdictions', type_='foreignkey')
    op.create_foreign_key(None, 'jurisdictions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'jurisdictions', 'jurisdictions', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_users_project_id_fkey'), 'project_users', type_='foreignkey')
    op.create_foreign_key(None, 'project_users', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_users', type_='foreignkey')
    op.create_foreign_key(op.f('project_users_project_id_fkey'), 'project_users', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'jurisdictions', type_='foreignkey')
    op.drop_constraint(None, 'jurisdictions', type_='foreignkey')
    op.create_foreign_key(op.f('jurisdictions_parent_id_fkey'), 'jurisdictions', 'jurisdictions', ['parent_id'], ['id'])
    op.create_foreign_key(op.f('jurisdictions_project_id_fkey'), 'jurisdictions', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
