"""Add scrape_job_id to revision_notifications

Revision ID: a436ec27108b
Revises: d227f5996841
Create Date: 2025-12-05 10:25:54.850225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a436ec27108b'
down_revision: Union[str, Sequence[str], None] = 'd227f5996841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revision_notifications', sa.Column('scrape_job_id', sa.Uuid(), nullable=True))
    op.create_index('ix_notifications_scrape_job', 'revision_notifications', ['scrape_job_id'], unique=False, postgresql_where=sa.text('scrape_job_id IS NOT NULL'))
    op.create_index(op.f('ix_revision_notifications_scrape_job_id'), 'revision_notifications', ['scrape_job_id'], unique=False)
    op.create_foreign_key(None, 'revision_notifications', 'scrape_jobs', ['scrape_job_id'], ['id'])
    op.create_index(op.f('ix_ticket_invited_users_ticket_id'), 'ticket_invited_users', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_invited_users_user_id'), 'ticket_invited_users', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_ticket_invited_users_user_id'), 'ticket_invited_users', type_='foreignkey')
    op.drop_constraint(op.f('fk_ticket_invited_users_ticket_id'), 'ticket_invited_users', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_invited_users', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'ticket_invited_users', 'tickets', ['ticket_id'], ['id'])
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_tickets_assigned_by_user_id'), 'tickets', ['assigned_by_user_id'], unique=False)
    op.create_index(op.f('ix_tickets_data_revision_id'), 'tickets', ['data_revision_id'], unique=False)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_source_id'), 'tickets', ['source_id'], unique=False)
    op.create_index(op.f('ix_tickets_title'), 'tickets', ['title'], unique=False)
    op.drop_constraint(op.f('fk_tickets_source_id'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_project_id'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_data_revision_id'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_assigned_by_user_id'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_assigned_to_user_id'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_organization_id'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_created_by_user_id'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'users', ['assigned_to_user_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'data_revisions', ['data_revision_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'sources', ['source_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'users', ['assigned_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tickets_created_by_user_id'), 'tickets', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_tickets_organization_id'), 'tickets', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_tickets_assigned_to_user_id'), 'tickets', 'users', ['assigned_to_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_tickets_assigned_by_user_id'), 'tickets', 'users', ['assigned_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_tickets_data_revision_id'), 'tickets', 'data_revisions', ['data_revision_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_tickets_project_id'), 'tickets', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_tickets_source_id'), 'tickets', 'sources', ['source_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_tickets_title'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_source_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_data_revision_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_by_user_id'), table_name='tickets')
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(None, 'ticket_invited_users', type_='foreignkey')
    op.drop_constraint(None, 'ticket_invited_users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ticket_invited_users_ticket_id'), 'ticket_invited_users', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_ticket_invited_users_user_id'), 'ticket_invited_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ticket_invited_users_user_id'), table_name='ticket_invited_users')
    op.drop_index(op.f('ix_ticket_invited_users_ticket_id'), table_name='ticket_invited_users')
    op.drop_constraint(None, 'revision_notifications', type_='foreignkey')
    op.drop_index(op.f('ix_revision_notifications_scrape_job_id'), table_name='revision_notifications')
    op.drop_index('ix_notifications_scrape_job', table_name='revision_notifications', postgresql_where=sa.text('scrape_job_id IS NOT NULL'))
    op.drop_column('revision_notifications', 'scrape_job_id')
    # ### end Alembic commands ###
