"""updated_at field in Jurisdiction model set to update automatically

Revision ID: a6550cc2c2fe
Revises: 568cc1b65e22
Create Date: 2025-11-22 08:09:20.318694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6550cc2c2fe'
down_revision: Union[str, Sequence[str], None] = '568cc1b65e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
