"""Add foreign key to sources.jurisdiction_id

Revision ID: ad84a17165f3
Revises: cba15a561885
Create Date: 2025-11-25 22:16:28.311143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad84a17165f3'
down_revision: Union[str, Sequence[str], None] = 'cba15a561885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'sources', 'jurisdictions', ['jurisdiction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    # ### end Alembic commands ###
