"""add ticket model

Revision ID: ae115e115796
Revises: c18bded7b6a0
Create Date: 2025-12-04 23:37:06.008827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae115e115796'
down_revision: Union[str, Sequence[str], None] = 'c18bded7b6a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Tickets table already exists in database - no changes needed for ticket model
    # Adding missing foreign key constraint on otps table
    op.create_foreign_key('fk_otps_user_id', 'otps', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_otps_user_id', 'otps', type_='foreignkey')
    # ### end Alembic commands ###
