"""add last_scraped_at and last_error to sources table

Revision ID: b52cbc0b1765
Revises: b7c40d70aa47
Create Date: 2025-11-28 00:08:16.352598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b52cbc0b1765'
down_revision: Union[str, Sequence[str], None] = 'b7c40d70aa47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('sources', sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True))
    # op.add_column('sources', sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('sources', 'last_error')
    # op.drop_column('sources', 'last_scraped_at')
    # ### end Alembic commands ###
