"""updated_at field in Jurisdiction updated for automatic db level update

Revision ID: bb476a7882b8
Revises: 568cc1b65e22
Create Date: 2025-11-22 10:54:05.238162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb476a7882b8'
down_revision: Union[str, Sequence[str], None] = '568cc1b65e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
