"""add source schema updates

Revision ID: c560d3ec4e46
Revises: 92b6d9686574
Create Date: 2025-11-26 14:16:51.410379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c560d3ec4e46'
down_revision: Union[str, Sequence[str], None] = '92b6d9686574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_revisions', 'ai_markdown_summary',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.add_column('sources', sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sources', sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('sources', 'next_scrape_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.create_foreign_key(None, 'sources', 'jurisdictions', ['jurisdiction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.alter_column('sources', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sources', 'next_scrape_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('sources', 'last_error')
    op.drop_column('sources', 'last_scraped_at')
    op.alter_column('data_revisions', 'ai_markdown_summary',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
