"""add org industry, user.auth_provider, role org_id + unique constraint

Revision ID: cb3b4d0a4684
Revises: 7ef99f328402
Create Date: 2025-11-18 09:19:55.195855

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "cb3b4d0a4684"
down_revision: Union[str, Sequence[str], None] = "7ef99f328402"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "waitlist_subscriber",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "signup_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "organization_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["organization_email"],
            ["waitlist.organization_email"],
        ),
        sa.PrimaryKeyConstraint("email"),
    )
    op.create_index(
        op.f("ix_waitlist_subscriber_email"),
        "waitlist_subscriber",
        ["email"],
        unique=False,
    )
    op.add_column(
        "organizations",
        sa.Column(
            "industry", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
    )
    op.add_column("roles", sa.Column("organization_id", sa.Uuid(), nullable=False))
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=False)
    op.create_index(
        op.f("ix_roles_organization_id"), "roles", ["organization_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_org_role_name", "roles", ["organization_id", "name"]
    )
    op.create_foreign_key(None, "roles", "organizations", ["organization_id"], ["id"])
    op.add_column(
        "users",
        sa.Column(
            "auth_provider", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "auth_provider")
    op.drop_constraint(None, "roles", type_="foreignkey")
    op.drop_constraint("uq_org_role_name", "roles", type_="unique")
    op.drop_index(op.f("ix_roles_organization_id"), table_name="roles")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.drop_column("roles", "organization_id")
    op.drop_column("organizations", "industry")
    op.drop_index(
        op.f("ix_waitlist_subscriber_email"), table_name="waitlist_subscriber"
    )
    op.drop_table("waitlist_subscriber")
    # ### end Alembic commands ###
