"""update data revision

Revision ID: cba15a561885
Revises: cbb75100ccd3
Create Date: 2025-11-24 17:25:00.928155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cba15a561885'
down_revision: Union[str, Sequence[str], None] = 'cbb75100ccd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_revisions', sa.Column('ai_markdown_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('data_revisions', sa.Column('ai_confidence_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_revisions', 'ai_confidence_score')
    op.drop_column('data_revisions', 'ai_markdown_summary')
    # ### end Alembic commands ###
