"""add_content_hash_to_data_revisions

Revision ID: cbb75100ccd3
Revises: 7d1fb4b20e75
Create Date: 2025-11-24 15:12:25.425744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb75100ccd3'
down_revision: Union[str, Sequence[str], None] = '7d1fb4b20e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_revisions', sa.Column('content_hash', sa.String(64), nullable=True))
    op.create_index(op.f('ix_data_revisions_content_hash'), 'data_revisions', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_revisions_content_hash'), table_name='data_revisions')
    op.drop_column('data_revisions', 'content_hash')
    # ### end Alembic commands ###
