"""Parent child relationship added for nested jurisdiction and name constraint to avoid duplicate name on the same project

Revision ID: d615ad7aed6e
Revises: 1c058123eea7
Create Date: 2025-11-25 02:08:25.151175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd615ad7aed6e'
down_revision: Union[str, Sequence[str], None] = '1c058123eea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_project_name', 'jurisdictions', ['project_id', 'name'])
    op.create_foreign_key(
        "fk_jurisdictions_parent_id",
        "jurisdictions",
        "jurisdictions",
        ["parent_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_project_name', 'jurisdictions', type_='unique')
    op.drop_constraint(
        "fk_jurisdictions_parent_id",
        "jurisdictions",
        type_="foreignkey",
    )
    # ### end Alembic commands ###
