"""updated parent_id to have a foreign key of jurisdiction id

Revision ID: d8683693bd9c
Revises: 96c08aa21047
Create Date: 2025-11-20 23:42:08.885503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8683693bd9c'
down_revision: Union[str, Sequence[str], None] = '96c08aa21047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'jurisdictions', 'jurisdictions', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jurisdictions', type_='foreignkey')
    # ### end Alembic commands ###
