"""add_ticket_notifications

Revision ID: da915e35b161
Revises: a249039be841
Create Date: 2025-12-05 21:09:35.243522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'da915e35b161'
down_revision: Union[str, Sequence[str], None] = 'a249039be841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_notifications',
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='ticketnotificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_ticket_notifications_notification_id'), 'ticket_notifications', ['notification_id'], unique=False)
    op.create_index(op.f('ix_ticket_notifications_ticket_id'), 'ticket_notifications', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_notifications_user_id'), 'ticket_notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_ticket_invited_users_ticket_id'), 'ticket_invited_users', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_invited_users_user_id'), 'ticket_invited_users', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_ticket_invited_users_ticket_id'), 'ticket_invited_users', type_='foreignkey')
    op.drop_constraint(op.f('fk_ticket_invited_users_user_id'), 'ticket_invited_users', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_invited_users', 'tickets', ['ticket_id'], ['id'])
    op.create_foreign_key(None, 'ticket_invited_users', 'users', ['user_id'], ['id'])
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_tickets_assigned_by_user_id'), 'tickets', ['assigned_by_user_id'], unique=False)
    op.create_index(op.f('ix_tickets_data_revision_id'), 'tickets', ['data_revision_id'], unique=False)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_source_id'), 'tickets', ['source_id'], unique=False)
    op.create_index(op.f('ix_tickets_title'), 'tickets', ['title'], unique=False)
    op.drop_constraint(op.f('fk_tickets_data_revision_id'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_source_id'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_assigned_to_user_id'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_organization_id'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_project_id'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_assigned_by_user_id'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_created_by_user_id'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'data_revisions', ['data_revision_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'users', ['assigned_by_user_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'users', ['assigned_to_user_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'sources', ['source_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tickets_created_by_user_id'), 'tickets', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_tickets_assigned_by_user_id'), 'tickets', 'users', ['assigned_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_tickets_project_id'), 'tickets', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_tickets_organization_id'), 'tickets', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_tickets_assigned_to_user_id'), 'tickets', 'users', ['assigned_to_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_tickets_source_id'), 'tickets', 'sources', ['source_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_tickets_data_revision_id'), 'tickets', 'data_revisions', ['data_revision_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_tickets_title'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_source_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_data_revision_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_by_user_id'), table_name='tickets')
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(None, 'ticket_invited_users', type_='foreignkey')
    op.drop_constraint(None, 'ticket_invited_users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ticket_invited_users_user_id'), 'ticket_invited_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_ticket_invited_users_ticket_id'), 'ticket_invited_users', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ticket_invited_users_user_id'), table_name='ticket_invited_users')
    op.drop_index(op.f('ix_ticket_invited_users_ticket_id'), table_name='ticket_invited_users')
    op.drop_index(op.f('ix_ticket_notifications_user_id'), table_name='ticket_notifications')
    op.drop_index(op.f('ix_ticket_notifications_ticket_id'), table_name='ticket_notifications')
    op.drop_index(op.f('ix_ticket_notifications_notification_id'), table_name='ticket_notifications')
    op.drop_table('ticket_notifications')
    # ### end Alembic commands ###
