"""update_role_permissions_jsonb_add_hierarchy

Revision ID: e25001a9ed6a
Revises: 6ab044401c2c
Create Date: 2025-12-04 02:45:17.486621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e25001a9ed6a'
down_revision: Union[str, Sequence[str], None] = '6ab044401c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('hierarchy_level', sa.Integer(), nullable=False))
    op.add_column('roles', sa.Column('template_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('roles', sa.Column('is_custom', sa.Boolean(), nullable=False))
    op.alter_column('roles', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.execute("UPDATE roles SET hierarchy_level = 1 WHERE hierarchy_level IS NULL")
    op.execute("UPDATE roles SET is_custom = false WHERE is_custom IS NULL")
    
    # Make NOT NULL
    op.alter_column('roles', 'hierarchy_level', nullable=False)
    op.alter_column('roles', 'is_custom', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('roles', 'is_custom')
    op.drop_column('roles', 'template_name')
    op.drop_column('roles', 'hierarchy_level')
    op.drop_constraint('fk_ba_default_payment_method_id', 'billing_accounts', type_='foreignkey')
    # ### end Alembic commands ###
